<a href="https://colab.research.google.com/github/kajalpanda1/ML-Assignments/blob/master/DataPreprocessing_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data={'Index':[1,2,3,4,5,6,7,8,9,10,11,12],'Age':[25,27,50,35,40,5,np.nan,34,21,45,np.nan,48],'Salary':[10000,30000,40000,50000,np.nan,45000,20000,np.nan,20000,19000,34000,30000]}
df=pd.DataFrame(data)

In [ ]:
df.head()

Index   Age   Salary
0      1  25.0  10000.0
1      2  27.0  30000.0
2      3  50.0  40000.0
3      4  35.0  50000.0
4      5  40.0      NaN

In [ ]:
X=df.iloc[:,:-1]
Y=df.iloc[:,-1:]

In [ ]:
X

Index   Age
0       1  25.0
1       2  27.0
2       3  50.0
3       4  35.0
4       5  40.0
5       6   5.0
6       7   NaN
7       8  34.0
8       9  21.0
9      10  45.0
10     11   NaN
11     12  48.0

In [ ]:
Y

Salary
0   10000.0
1   30000.0
2   40000.0
3   50000.0
4       NaN
5   45000.0
6   20000.0
7       NaN
8   20000.0
9   19000.0
10  34000.0
11  30000.0

In [ ]:
from sklearn.impute import SimpleImputer
imp=SimpleImputer(missing_values=np.nan,strategy='mean')

In [ ]:
X=imp.fit_transform(X)

In [ ]:
X

array([[ 1., 25.],
       [ 2., 27.],
       [ 3., 50.],
       [ 4., 35.],
       [ 5., 40.],
       [ 6.,  5.],
       [ 7., 33.],
       [ 8., 34.],
       [ 9., 21.],
       [10., 45.],
       [11., 33.],
       [12., 48.]])

In [ ]:
Y=imp.fit_transform(Y)

In [ ]:
Y

array([[10000.],
       [30000.],
       [40000.],
       [50000.],
       [29800.],
       [45000.],
       [20000.],
       [29800.],
       [20000.],
       [19000.],
       [34000.],
       [30000.]])

In [ ]:
imp1=SimpleImputer(missing_values=np.nan,strategy='most_frequent')

In [ ]:
X1=imp1.fit_transform(X)
Y1=imp1.fit_transform(Y)

In [ ]:
imp2=SimpleImputer(missing_values=np.nan,strategy='constant',fill_value=-99)

In [ ]:
X2=imp2.fit_transform(X)

In [ ]:
X2

array([[ 1., 25.],
       [ 2., 27.],
       [ 3., 50.],
       [ 4., 35.],
       [ 5., 40.],
       [ 6.,  5.],
       [ 7., 99.],
       [ 8., 34.],
       [ 9., 21.],
       [10., 45.],
       [11., 99.],
       [12., 48.]])

In [ ]:
Y2=imp2.fit_transform(Y)

In [ ]:
Y2

array([[10000.],
       [30000.],
       [40000.],
       [50000.],
       [  -99.],
       [45000.],
       [20000.],
       [  -99.],
       [20000.],
       [19000.],
       [34000.],
       [30000.]])

In [ ]:
data1={'Index':[1,2,3,4,5,6],'Country':['JAPAN','US','INDIA','CHINA','US','INDIA'],'Capital':['Tokyo','NewYork','Delhi','Beijing','NewYork','Delhi']}
df1=pd.DataFrame(data1)

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
l=LabelEncoder()

In [ ]:
df1['Country']=l.fit_transform(df1['Country'])

In [ ]:
df1.shape

(6, 3)

In [ ]:
df1['Country']=l.inverse_transform(df1['Country'])

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
oh=OneHotEncoder()

In [ ]:
df1=oh.fit_transform(df1)

In [ ]:
df1

<6x14 sparse matrix of type '<class 'numpy.float64'>'
	with 18 stored elements in Compressed Sparse Row format>

In [ ]:
df1.toarray().shape

(6, 14)